### ISSUE TITLE
Slider displays incorrect input value

### ISSUE THREAD

**Issue by Lortseam** [Siphalor/coat#3]
I have the following slider with a minimum of 5 and a maximum of 20:
![image](https://user-images.githubusercontent.com/77894793/154727109-46200724-fda2-453d-9602-423bdb77c1bb.png)
After saving and reopening the screen, the slider looks like this:
![image](https://user-images.githubusercontent.com/77894793/154727475-c789669c-a295-40f1-a8a7-e0de9e08fa6a.png)
(I have added that warning message myself)

---

After taking a look at the code, it looks like the `SliderConfigInput` passes an invalid value to the `SliderWidget`, as the latter excepts a value between 0 and 1. Instead, the real value is passed to widget.

**Comment by Siphalor** [comment]
You're completely right.
This only applies to the constructor though, `setValue` already correctly calculated the internal slider value.
That's probably why I haven't noticed it so far, as Tweed relies on that iirc.

The fix is coming soon :)

**Comment by Siphalor** [comment]
Fixed in b0e32819a9fdc7e38f80c2ae03980da90ec509e4. Just mentioned the wrong issue ^^
